# This is a basic workflow to help you get started with Actions

name: Run jest tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "gh-pages" branch
  push:
    branches: ["gh-pages"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: run ci
        run: npm ci

      - name: run jest
        run: npm test

      - name: tests passed
        if: ${{ success() }}
        run: echo tests passed

      - name: tests failed
        if: ${{ failure() }}
        run: echo tests failed
